server:
  host: "0.0.0.0"
  port: 8080
  imagePath: "/app"              # 图片保存路径
  imageBaseUrl: "http://localhost:8080"   # 图片的网络访问基路径

mysql:
  dataSourceName: "root:yangyt66@(mysql:3306)/blog?charset=utf8mb4&parseTime=true&loc=Local"
  maxOpenConns: 20     # 连接池最大连接数
  maxIdleConns: 10     # 连接池最大空闲连接数

log:
  filepath: "./logs"
  filename: "blog.log"
  toFile: true
  level: "INFO"

aliOSS:
  endPoint: "yourEndPoint"               # 注意：在填写endPoint时要使用带有bucketName的地址，否则会上传失败，例如：my-upload.oss-cn-beijing.aliyuncs.com，前面无需加http
  accessKeyId: "yourAccessKeyId"
  accessKeySecret: "yourAccessKeySecret"
  bucket: "yourBucket"
  maxImageSize: 5242880                  # 5M 上传的最大图片大小，如果大于该文件大小，将会对图片进行压缩